[build]
  functions = "netlify/functions"  # Path to your functions directory
  publish = "public"                # Directory for static files (adjust as needed)

[[redirects]]
  from = "/showpage"
  to = "/.netlify/functions/showpage"
  status = 200
  force = true
